"""M1 Day 4: Model Explainability Layer for Multi-Horizon Flood-Risk Predictions.

Provides deterministic, lightweight feature attribution, static vs. dynamic decomposition,
and human-readable explanations for XGBoost flood-risk predictions across +1h, +3h, and +6h.

SCIENTIFIC PROVENANCE & CAUSAL DISCLAIMER:
Explanations generated by this module reflect statistical feature attributions and empirical
threshold contributions derived from the prototype XGBoost model and calibrated proxy datasets.
They do NOT assert proven physical or hydraulic causation.
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence, Union

logger = logging.getLogger(__name__)

SCIENTIFIC_DISCLAIMER = (
    "Scientific provenance and non-causal disclaimer: Explanations reflect model-associated "
    "feature contributions and empirical thresholds, NOT proven physical causation. "
    "Prototype system trained on calibrated proxy development data."
)

FEATURE_METADATA: Dict[str, Dict[str, str]] = {
    "rainfall_mm": {
        "display_name": "Forecast Rainfall",
        "category": "dynamic",
        "unit": "mm",
        "description": "Cumulative precipitation forecast for the requested horizon window",
    },
    "rain_past_24h": {
        "display_name": "Antecedent 24h Rainfall",
        "category": "dynamic",
        "unit": "mm",
        "description": "Antecedent 24-hour precipitation indicating prior soil saturation",
    },
    "vulnerability_score": {
        "display_name": "Static Vulnerability",
        "category": "static",
        "unit": "score",
        "description": "M1 Day 2 composite static terrain and environmental vulnerability score",
    },
    "elevation": {
        "display_name": "Terrain Elevation",
        "category": "static",
        "unit": "m AMSL",
        "description": "Ground surface elevation above mean sea level from 30m DEM",
    },
    "slope": {
        "display_name": "Terrain Slope",
        "category": "static",
        "unit": "degrees",
        "description": "Ground surface inclination; flatter terrain impedes drainage discharge",
    },
    "flow_accumulation": {
        "display_name": "Catchment Flow Accumulation",
        "category": "static",
        "unit": "cells",
        "description": "Upstream overland drainage catchment contributing surface runoff to cell",
    },
    "imperviousness": {
        "display_name": "Surface Imperviousness",
        "category": "static",
        "unit": "fraction",
        "description": "Proportion of artificial, sealed, and paved urban surface preventing infiltration",
    },
    "trigger_rain_threshold": {
        "display_name": "Critical Trigger Threshold",
        "category": "hotspot_context",
        "unit": "mm",
        "description": "Calibrated critical precipitation threshold for onset of waterlogging",
    },
    "is_hotspot": {
        "display_name": "Chronic Hotspot Status",
        "category": "hotspot_context",
        "unit": "flag",
        "description": "Indicator of whether location is an officially documented chronic flood hotspot",
    },
}


@dataclass
class FactorContribution:
    """Individual factor contribution to a flood-risk prediction."""
    feature: str
    display_name: str
    category: str  # 'dynamic', 'static', 'hotspot_context'
    importance: float  # Relative normalized importance share [0.0, 1.0]
    direction: str  # 'increases_risk', 'decreases_risk', 'neutral'
    value: float
    unit: str
    description: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PredictionExplanation:
    """Complete explainability output for a single cell risk prediction."""
    cell_id: str
    timestamp: str
    horizon: int
    risk_level: str
    probability: float
    top_factors: List[FactorContribution]
    static_factors: Dict[str, Any]
    dynamic_factors: Dict[str, Any]
    hotspot_context: Dict[str, Any]
    summary: str
    methodology: str = "deterministic_feature_attribution"
    disclaimer: str = SCIENTIFIC_DISCLAIMER

    def to_dict(self) -> Dict[str, Any]:
        return {
            "cell_id": self.cell_id,
            "timestamp": self.timestamp,
            "horizon": self.horizon,
            "risk_level": self.risk_level,
            "probability": self.probability,
            "top_factors": [f.to_dict() for f in self.top_factors],
            "static_factors": self.static_factors,
            "dynamic_factors": self.dynamic_factors,
            "hotspot_context": self.hotspot_context,
            "summary": self.summary,
            "methodology": self.methodology,
            "disclaimer": self.disclaimer,
        }


def generate_human_readable_summary(
    risk_level: str,
    probability: float,
    horizon: int,
    rainfall_mm: float,
    vulnerability_score: float,
    rain_past_24h: float = 0.0,
    is_hotspot: bool = False,
    cell_id: str = "",
) -> str:
    """Generates an objective, deterministic summary of the prediction without exaggerated claims."""
    level = str(risk_level).upper()
    r = float(rainfall_mm)
    v = float(vulnerability_score)
    rp = float(rain_past_24h)
    h = int(horizon)

    # 1. Rainfall characterization
    if level == "HIGH" or r >= 40.0:
        rain_desc = f"High forecast rainfall ({r:.1f} mm in +{h}h)"
    elif level == "MEDIUM" or r >= 15.0:
        rain_desc = f"Moderate forecast rainfall ({r:.1f} mm in +{h}h)"
    else:
        rain_desc = f"Low forecast rainfall ({r:.1f} mm in +{h}h)"

    # 2. Terrain vulnerability characterization
    if v >= 0.70:
        vuln_desc = f"high static terrain vulnerability ({v:.2f})"
    elif v >= 0.40:
        vuln_desc = f"moderate static terrain vulnerability ({v:.2f})"
    else:
        vuln_desc = f"low static terrain vulnerability ({v:.2f})"

    # 3. Hotspot context
    hotspot_str = " at a documented chronic waterlogging hotspot" if is_hotspot else ""

    # 4. Antecedent moisture clause
    antecedent_str = ""
    if rp >= 35.0:
        antecedent_str = f", compounded by saturated ground conditions ({rp:.1f} mm of antecedent rainfall)"
    elif rp >= 15.0:
        antecedent_str = f", with moderate antecedent precipitation ({rp:.1f} mm in past 24h)"

    # 5. Synthesis by risk level
    if level == "HIGH":
        summary = (
            f"{rain_desc} combined with {vuln_desc}{hotspot_str}{antecedent_str} "
            f"indicates elevated flood probability (p={probability:.2f})."
        )
    elif level == "MEDIUM":
        summary = (
            f"{rain_desc} combined with {vuln_desc}{hotspot_str}{antecedent_str} "
            f"indicates moderate flood risk (p={probability:.2f}) warranting monitoring."
        )
    else:
        summary = (
            f"{rain_desc} over {vuln_desc}{hotspot_str}{antecedent_str} "
            f"indicates low flood probability (p={probability:.2f}) under current conditions."
        )

    return summary


def explain_prediction(
    feature_dict: Dict[str, float],
    feature_importances: Dict[str, float],
    risk_level: str,
    probability: float,
    horizon: int,
    cell_id: str,
    timestamp: Optional[str] = None,
    top_n: int = 5,
) -> PredictionExplanation:
    """Computes a lightweight, deterministic explanation for a flood-risk prediction.

    Combines model-level feature importances with local feature values and baseline thresholds
    to determine the direction and relative local contribution of each feature.
    """
    ts = timestamp or datetime.now(timezone.utc).isoformat()
    h = int(horizon)
    level = str(risk_level).upper()
    prob = float(probability)

    rainfall_mm = float(feature_dict.get("rainfall_mm", 0.0))
    rain_past_24h = float(feature_dict.get("rain_past_24h", 0.0))
    vulnerability_score = float(feature_dict.get("vulnerability_score", 0.50))
    elevation = float(feature_dict.get("elevation", 10.0))
    slope = float(feature_dict.get("slope", 1.0))
    flow_acc = float(feature_dict.get("flow_accumulation", 1000.0))
    imperviousness = float(feature_dict.get("imperviousness", 0.60))
    trigger_thresh = float(feature_dict.get("trigger_rain_threshold", 35.0))
    is_hotspot_val = float(feature_dict.get("is_hotspot", 0.0))
    is_hotspot_bool = is_hotspot_val >= 0.5

    # Determine direction and normalized local deviation for each feature
    directions: Dict[str, str] = {}
    local_weights: Dict[str, float] = {}

    for feat_name, meta in FEATURE_METADATA.items():
        val = float(feature_dict.get(feat_name, 0.0))
        base_imp = float(feature_importances.get(feat_name, 0.05))
        # Ensure a minimal positive baseline importance
        base_imp = max(0.005, base_imp)

        # Direction logic based on physical hydrology
        if feat_name == "rainfall_mm":
            ratio = val / max(1.0, trigger_thresh)
            if ratio >= 0.80 or val >= 25.0:
                direction = "increases_risk"
                mult = 1.0 + min(2.0, ratio)
            elif val <= 5.0:
                direction = "decreases_risk"
                mult = 1.5
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "vulnerability_score":
            if val >= 0.60:
                direction = "increases_risk"
                mult = 1.0 + (val - 0.50) * 2.0
            elif val < 0.40:
                direction = "decreases_risk"
                mult = 1.0 + (0.50 - val) * 2.0
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "rain_past_24h":
            if val >= 25.0:
                direction = "increases_risk"
                mult = 1.0 + min(1.5, val / 40.0)
            elif val <= 5.0:
                direction = "decreases_risk"
                mult = 1.2
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "elevation":
            if val <= 7.0:
                direction = "increases_risk"
                mult = 1.4
            elif val >= 15.0:
                direction = "decreases_risk"
                mult = 1.4
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "slope":
            if val <= 0.3:
                direction = "increases_risk"
                mult = 1.3
            elif val >= 1.5:
                direction = "decreases_risk"
                mult = 1.3
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "flow_accumulation":
            if val >= 50000.0:
                direction = "increases_risk"
                mult = 1.3
            elif val <= 5000.0:
                direction = "decreases_risk"
                mult = 1.2
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "imperviousness":
            if val >= 0.75:
                direction = "increases_risk"
                mult = 1.3
            elif val <= 0.45:
                direction = "decreases_risk"
                mult = 1.2
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "trigger_rain_threshold":
            if val <= 30.0:
                direction = "increases_risk"
                mult = 1.2
            elif val >= 50.0:
                direction = "decreases_risk"
                mult = 1.2
            else:
                direction = "neutral"
                mult = 1.0

        elif feat_name == "is_hotspot":
            if val >= 0.5:
                direction = "increases_risk"
                mult = 1.4
            else:
                direction = "neutral"
                mult = 0.8
        else:
            direction = "neutral"
            mult = 1.0

        directions[feat_name] = direction
        local_weights[feat_name] = base_imp * mult

    # Normalize local weights so they sum to 1.0
    total_local_w = sum(local_weights.values()) or 1.0
    normalized_shares = {k: round(v / total_local_w, 4) for k, v in local_weights.items()}

    # Construct FactorContribution objects
    all_factors: List[FactorContribution] = []
    for feat_name, meta in FEATURE_METADATA.items():
        all_factors.append(
            FactorContribution(
                feature=feat_name,
                display_name=meta["display_name"],
                category=meta["category"],
                importance=normalized_shares[feat_name],
                direction=directions[feat_name],
                value=round(float(feature_dict.get(feat_name, 0.0)), 2),
                unit=meta["unit"],
                description=meta["description"],
            )
        )

    # Sort factors by importance descending
    all_factors.sort(key=lambda x: x.importance, reverse=True)
    top_factors = all_factors[:top_n]

    # Decompose into structured static, dynamic, and hotspot components
    static_factors = {
        "vulnerability_score": round(vulnerability_score, 4),
        "elevation_m": round(elevation, 2),
        "slope_deg": round(slope, 2),
        "flow_accumulation": round(flow_acc, 1),
        "imperviousness": round(imperviousness, 3),
        "static_contributions": {
            "elevation": round(0.35 * max(0.0, min(1.0, (25.0 - elevation) / 20.0)), 4),
            "slope": round(0.15 * max(0.0, min(1.0, (3.0 - slope) / 3.0)), 4),
            "flow_accumulation": round(0.25 * min(1.0, flow_acc / 100000.0), 4),
            "imperviousness": round(0.25 * imperviousness, 4),
        },
    }

    dynamic_factors = {
        "rainfall_mm": round(rainfall_mm, 2),
        "horizon_hours": h,
        "rain_past_24h_mm": round(rain_past_24h, 2),
        "threshold_ratio": round(rainfall_mm / max(1.0, trigger_thresh), 2),
    }

    hotspot_context = {
        "is_hotspot": is_hotspot_bool,
        "trigger_threshold_mm": round(trigger_thresh, 2),
    }

    summary = generate_human_readable_summary(
        risk_level=level,
        probability=prob,
        horizon=h,
        rainfall_mm=rainfall_mm,
        vulnerability_score=vulnerability_score,
        rain_past_24h=rain_past_24h,
        is_hotspot=is_hotspot_bool,
        cell_id=cell_id,
    )

    return PredictionExplanation(
        cell_id=str(cell_id),
        timestamp=str(ts),
        horizon=h,
        risk_level=level,
        probability=round(prob, 4),
        top_factors=top_factors,
        static_factors=static_factors,
        dynamic_factors=dynamic_factors,
        hotspot_context=hotspot_context,
        summary=summary,
        methodology="deterministic_feature_attribution",
        disclaimer=SCIENTIFIC_DISCLAIMER,
    )
