"""Static terrain and vulnerability processing package for Chetna."""

from src.static_risk.historical_rain import fetch_archive_rainfall
from src.static_risk.hotspots import (
    DEFAULT_HOTSPOT_CELL_MAPPING,
    DEFAULT_M1_DATA_DIR,
    BacktestEvent,
    HistoricalRainfallRecord,
    HistoricalRainfallSeries,
    Hotspot,
    HotspotEventObservation,
    M1DevelopmentDataset,
    generate_m1_development_dataset,
    get_backtest_event_by_id,
    get_hotspot_by_id,
    init_hotspot_tables,
    load_backtest_events,
    load_backtest_events_from_db,
    load_historical_rainfall,
    load_hotspot_observations_from_db,
    load_hotspots,
    load_hotspots_from_db,
    load_m1_development_dataset,
    save_backtest_events_to_db,
    save_hotspot_observations_to_db,
    save_hotspots_to_db,
    save_m1_dataset_to_db,
)
from src.static_risk.vulnerability import (
    DEFAULT_THRESHOLDS,
    DEFAULT_WEIGHTS,
    CellStaticRisk,
    StaticRiskGridResult,
    calculate_cell_vulnerability,
    classify_risk_score,
    compute_static_vulnerability,
    load_grid_from_sqlite,
    normalize_elevation,
    normalize_flow_accumulation,
    normalize_imperviousness,
    normalize_slope,
    process_static_risk_grid,
)


__all__ = [
    "DEFAULT_M1_DATA_DIR",
    "DEFAULT_HOTSPOT_CELL_MAPPING",
    "Hotspot",
    "BacktestEvent",
    "HistoricalRainfallRecord",
    "HistoricalRainfallSeries",
    "HotspotEventObservation",
    "M1DevelopmentDataset",
    "load_hotspots",
    "get_hotspot_by_id",
    "load_backtest_events",
    "get_backtest_event_by_id",
    "load_historical_rainfall",
    "generate_m1_development_dataset",
    "load_m1_development_dataset",
    "init_hotspot_tables",
    "save_hotspots_to_db",
    "save_backtest_events_to_db",
    "save_hotspot_observations_to_db",
    "save_m1_dataset_to_db",
    "load_hotspots_from_db",
    "load_backtest_events_from_db",
    "load_hotspot_observations_from_db",
    "fetch_archive_rainfall",
    "DEFAULT_WEIGHTS",
    "DEFAULT_THRESHOLDS",
    "CellStaticRisk",
    "StaticRiskGridResult",
    "normalize_elevation",
    "normalize_slope",
    "normalize_flow_accumulation",
    "normalize_imperviousness",
    "classify_risk_score",
    "calculate_cell_vulnerability",
    "process_static_risk_grid",
    "compute_static_vulnerability",
    "load_grid_from_sqlite",
]
